### ISSUE TITLE
[Annotation] total vs. per-variant sample size

### ISSUE THREAD

**Issue by jbao** [bookingcom/powercalculator#5]
First off, thanks for this wonderful tool.

I've got a question regarding the UI where it shows the total and daily number of visitors. I think it's slightly confusing whether it refers to the total or per-variant sample size. Maybe it's better to be more explicit about that?

Another stretchy feature could be some widget to configure the split ratio, instead of the default 50:50.

**Comment by Askoth** [comment]
Hello!

1 - We work with total in both fields. You have a good point there. Maybe we will have to revisit when we allow multi variant.

2 - We have that in the backlog but the calculation is a bit different from what we have now. Unfortunately I can't promise a date for it. I created another issue for it https://github.com/bookingcom/powercalculator/issues/6

**Comment by Askoth** [comment]
Closing this one due to inactivity
